# apiVersion: skaffold/v1beta2
apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  # remove from image: eu.gcr.io/
  # because:
  # time="2019-05-28T10:36:38Z" level=fatal msg="build failed: building [eu.gcr.io/dev-infra-240819/goqs]: build artifact: unknown: Project 'project:eu.gcr.io:dev-infra-240819' not found or deleted."
  - image: dev-infra-240819/goqs
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
      # relevant for `skaffold dev`
      # template: 'eu.gcr.io/{{.IMAGE_NAME}}:skaffold'
      # :skaffold doesn't always pull the latest
      # template: 'eu.gcr.io/{{.IMAGE_NAME}}@sha256:{{.VERSION}}'

  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    # tagPolicy:
    #   envTemplate:
    #     # template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.DIGEST_HEX}}'
    #     # template: 'eu.gcr.io/{{.IMAGE_NAME}}:skaffold'
    #     # template: 'eu.gcr.io/{{.IMAGE_NAME}}@sha256:{{.VERSION}}'
    #     template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.DIGEST}}'
    tagPolicy:
        sha256: {}
    artifacts:
    - image: eu.gcr.io/dev-infra-240819/goqs
    local: {}
  deploy:
    helm:
      releases:
      - name: goqs
        chartPath: charts/goqs
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '{{.DIGEST_HEX}}'
          # image.tag: '{{.DIGEST}}'
